pre-release-commit-message = "chore: Release"
no-dev-version = true
tag-message = "{{tag_name}}"
tag-name = "{{prefix}}v{{version}}"
consolidate-commits = true
consolidate-pushes = true
pre-release-replacements = [
    {file="doc/mcup.adoc", search=":release-version: [a-z0-9\\.-]+", replace=":release-version: {{version}}"},
    {file="CHANGELOG.md", search="Unreleased", replace="{{version}}", min=1},
    {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
    {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}", min=1},
    {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] - ReleaseDate\n", exactly=1},
    {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/hpehl/mcup/compare/{{tag_name}}...HEAD", exactly=1},
]
